name: CI Pipeline

on:
  pull_request:
    branches: [ "develop", "main" ]
  push:
    branches: [ "develop", "main" ]
# trigger for develop and main branch 
jobs:
  backend-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        working-directory: backend/api
        run: npm install

      - name: Run Unit Tests
        working-directory: backend/api
        run: npm run test -- --ci --reporters=default --reporters=jest-junit

      - name: Run Lint
        working-directory: backend/api
        run: npm run lint || echo "Lint not configured yet"

      - name: Build Backend
        working-directory: backend/api
        run: npm run build
